"""
Policy Advisor workflow definition.
"""

from __future__ import annotations

from typing import Any

REQUIRED_SLOTS = ["vehicle_idv_rs", "vehicle_age_years", "vehicle_segment"]

EXTRACTABLE_PROFILE_FIELDS = [
    "name",
    "vehicle_idv_rs",
    "vehicle_age_years",
    "fuel_type",
    "ev_flag",
    "annual_mileage_km",
    "ncb_percent",
    "residence_cluster",
    "vehicle_registration_number",
    "city_risk_band",
    "flood_risk_band",
    "commute_pattern",
    "financed_vehicle",
    "family_usage",
    "dependents",
    "vehicle_segment",
    "protection_preference",
    "wants_lowest_price",
    "coverage_priorities",
    "prefers_cashless",
    "theft_history",
    "previous_claims_3yr",
    "at_fault_claims_3yr",
    "traffic_violations_3yr",
    "anti_theft_device",
    "adas_level",
    "parking_type",
    "driving_experience_years",
    "insurance_history_years",
    "digital_affinity_1to5",
    "telematics_opt_in",
    "prior_policy_lapse",
    "needs_plain_language_1to5",
    "age",
    "is_chitchat_only",
    "is_followup_question",
    "is_asking_about_assistant",
    "_last_shown_summary",
    "_last_shown_policy_ids",
    "policy_id_a",
    "policy_id_b",
]

POLICY_ADVISOR_WORKFLOW: dict[str, Any] = {
    "name": "policy_advisor",
    "version": "7.0.0",
    "entry_node": "start",
    "nodes": [
        {"id": "start", "name": "Start", "node_type": "start"},
        {
            "id": "ensure_session",
            "name": "Ensure Session Identifier",
            "node_type": "task",
            "outputs": ["session_id"],
        },
        {
            "id": "extract_and_merge_profile",
            "name": "Extract And Merge Customer Profile",
            "node_type": "memory",
            "outputs": EXTRACTABLE_PROFILE_FIELDS,
        },
        {
            "id": "check_slots",
            "name": "Check Required Slots And Route",
            "node_type": "decision",
            "outputs": [
                "should_answer_about_assistant",
                "should_answer_followup",
                "should_ask_clarifying",
                "should_compare",
                "should_recommend",
            ],
        },
        {
            "id": "answer_about_assistant",
            "name": "Answer Question About The Assistant",
            "node_type": "llm",
            "configuration": {"prompt_kind": "answer_about_assistant"},
            "outputs": ["response_text"],
        },
        {
            "id": "answer_followup",
            "name": "Answer Follow-up Question",
            "node_type": "llm",
            "configuration": {"prompt_kind": "answer_followup"},
            "outputs": ["response_text"],
        },
        {
            "id": "ask_clarifying_question",
            "name": "Ask Clarifying Question",
            "node_type": "llm",
            "configuration": {"prompt_kind": "ask_clarifying_question"},
            "outputs": ["response_text"],
        },
        {
            "id": "get_recommendations",
            "name": "Get Policy Recommendations",
            "node_type": "tool",
            "configuration": {"tool_name": "recommend_policies"},
            "outputs": [
                "recommendations_result", "risk_assessment", "vehicle_category",
            ],
        },
        {
            "id": "format_explanation",
            "name": "Format Explanation",
            "node_type": "llm",
            "configuration": {"prompt_kind": "format_explanation"},
            "outputs": ["response_text"],
        },
        {
            "id": "get_comparison",
            "name": "Get Policy Comparison",
            "node_type": "tool",
            "configuration": {"tool_name": "compare_policies"},
            "outputs": [
                "comparison_result", "risk_assessment", "vehicle_category",
            ],
        },
        {
            "id": "format_comparison",
            "name": "Format Comparison Explanation",
            "node_type": "llm",
            "configuration": {"prompt_kind": "format_comparison"},
            "outputs": ["response_text"],
        },
        {"id": "end_about_assistant", "name": "End (Answered About Assistant)", "node_type": "end"},
        {"id": "end_followup", "name": "End (Answered Follow-up)", "node_type": "end"},
        {"id": "end_ask", "name": "End (Asked Clarifying Question)", "node_type": "end"},
        {"id": "end_recommend", "name": "End (Recommended)", "node_type": "end"},
        {"id": "end_compare", "name": "End (Compared)", "node_type": "end"},
    ],
    "edges": [
        {"source": "start", "destination": "ensure_session"},
        {"source": "ensure_session", "destination": "extract_and_merge_profile"},
        {"source": "extract_and_merge_profile", "destination": "check_slots"},
        {
            "source": "check_slots",
            "destination": "answer_about_assistant",
            "condition": "should_answer_about_assistant",
        },
        {
            "source": "check_slots",
            "destination": "answer_followup",
            "condition": "should_answer_followup",
        },
        {
            "source": "check_slots",
            "destination": "ask_clarifying_question",
            "condition": "should_ask_clarifying",
        },
        {
            "source": "check_slots",
            "destination": "get_comparison",
            "condition": "should_compare",
        },
        {
            "source": "check_slots",
            "destination": "get_recommendations",
            "condition": "should_recommend",
        },
        {"source": "answer_about_assistant", "destination": "end_about_assistant"},
        {"source": "answer_followup", "destination": "end_followup"},
        {"source": "ask_clarifying_question", "destination": "end_ask"},
        {"source": "get_recommendations", "destination": "format_explanation"},
        {"source": "format_explanation", "destination": "end_recommend"},
        {"source": "get_comparison", "destination": "format_comparison"},
        {"source": "format_comparison", "destination": "end_compare"},
    ],
}